### PR TITLE
Dev gnm

### PR DESCRIPTION
**Pull request by gmirsky**
Added exclusions and documentation to .gitignore file. 

Modularized tagging to make it automatic and centralized yet the user is able to add more tags if desired.

### CODE REVIEW

**Comment by SebastianUA** [comment]
Hi @gmirsky,

Thank you very much for your contribution!

Before I'm merging, I have a question for you:

Why you have changed `var.tags` to `module.aws_user_tags.tags`?

It looks like a module in the module.

If be honest, we can use the next approch and add the next lines examples/main.tf without any changes inside the AWS Glue module:
```
tags = merge(
	map(
    	"cost-center", "00-00000.000.01",
    	"Project", "My Test Glue Project"
  	),
  	local.tags
 )
```
Or:
```
tags = merge(
	map(
    	"cost-center", "00-00000.000.01",
    	"Project", "My Test Glue Project"
  	),
  	module.aws_user_tags.tags
 )
```

Please let me know what do you think about the module in module approach. 

I haven't done it before.  

Thanks

**Comment by gmirsky** [comment]
var.tags gets ingested into the aws_user_tags module and added to the tags it generates. module.aws_user_tags.tags outputs the combined collection of all the tags together.

I've found from my work scripting terraform that modularizing even the mundane things inside of modules makes code reusability easier. Half the time I just cut and paste sub-modules. Like I did with this one. 

Including the aws_user_tags module inside the Glue module allows us to wrap it and make it less confusing for the end terraform user using the Glue module.  I have already encountered such problems with such modules that I have deployed for my employer with more novice terraform programmers. Sort of the old KISS principle, Keep It Stupidly Simple. Though with Terraform some things are never really simple.

I can go either way. This is your creation. I am just helping out. ;-) I'll respect your decision as long as the result works

I'd like to try scripting up the "admin-role" next in the example to get the example ready to run "right out of the box" and then move on to the items referenced in the buckets.

**Comment by SebastianUA** [comment]
That's a bargain! :)

@gmirsky, Please let me know when we will create a tag.
Thank you!

**Comment by SebastianUA** [comment]
@gmirsky, Please let me know when we will create a tag.

**Comment by gmirsky** [comment]
Send me what you have been working with in the module for data, roles , etc. and I will script it up. You send it to me at gmirsky@gmail.com

It may have to wait until next weekend. I have a heavy week scheduled at work next week.

**Pull request merged**
